disable certificate validation via ENV variable
avenga/couper-oidc-gateway pull request #10
Opened 2021-12-21 13:42 UTC by johakoch

Set `DISABLE_CERTIFICATE_VALIDATION = true` to disable certificate validation

2021-12-22 09:18 UTC, filex requested changes
We should change the variable names. not only the new one, but all variables that affect the couper `backend` definition:

```
ORIGIN -> BACKEND_ORIGIN
ORIGIN_HOSTNAME -> BACKEND_HOSTNAME
*_TIMEOUT -> BACKEND_*_TIMEOUT
DISABLE_CERTIFICATE_VALIDATION -> BACKEND_DISABLE_CERTIFICATE_VALIDATION
```

2022-01-06 12:57 UTC, malud requested changes

2022-01-06 12:57 UTC, malud commented on couper.hcl
> +        disable_certificate_validation = env.BACKEND_DISABLE_CERTIFICATE_VALIDATION
The environment string mapping from string `true` or `false` to a boolean one is supported for the `settings` block only. So in this case the assignment must be slightly changed.
```suggestion
        disable_certificate_validation = env.BACKEND_DISABLE_CERTIFICATE_VALIDATION == "true"
```

2022-01-06 12:57 UTC, malud commented on README.md
> +| `BACKEND_DISABLE_CERTIFICATE_VALIDATION` | bool | `false` | Disables the peer certificate validation for the protected service | - |
```suggestion
| `BACKEND_DISABLE_CERTIFICATE_VALIDATION` | string | `false` | Disables the peer certificate validation for the protected service | - |
```

2022-01-06 12:57 UTC, malud commented on couper.hcl
> +    BACKEND_DISABLE_CERTIFICATE_VALIDATION = false
```suggestion
    BACKEND_DISABLE_CERTIFICATE_VALIDATION = "false"
```

2022-01-06 15:07 UTC, merged